name: Build and release

on:
  push:
    tags:
      - 'vsch*'
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: OpenBlock Desktop ${{ steps.tag.outputs.tag }}
          body: |
            ## Change Log (en)

            - **New feature**

                1. Feature 1.
                2. Feature 2.

            - **Fix bug**

                1. Bug 1.
                2. Bug 2.

            ## 更改日志 (zh-cn)

            - **新功能**

                1. 功能1。
                2. 功能2。

            - **修复错误**

                1. 错误1。
                2. 错误2。
          draft: true
          prerelease: false

  build-windows:
    needs: create-release
    runs-on: windows-2019
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: blocks Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-blocks
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-blocks
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x' 
          architecture: 'x64'
      - run: |
          cd openblock-blocks
          npm ci
          npm link

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          architecture: 'x64'

      - name: link Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-link
          ref: refs/heads/qdp
          token: ${{ secrets.GH_PAT }}
          path: openblock-link
      - run: |
          cd openblock-link
          npm ci
          npm link

      - name: resource Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-resource
          ref: refs/heads/qdp
          token: ${{ secrets.GH_PAT }}
          path: openblock-resource
      - run: |
          cd openblock-resource
          npm ci
          npm link

      - name: resource-cli Install
        uses: actions/checkout@v2
        with:
          repository: aopu-edu/openblock-resource-cli
          ref: refs/heads/main
          token: ${{ secrets.GH_PAT }}
          path: openblock-resource-cli
      - run: |
          cd openblock-resource-cli
          npm ci
          npm link

      - name: vm Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-vm
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-vm  
      - run: |
          cd openblock-vm
          npm ci
          npm link
          cd node_modules
          replace-tfhub

      - name: l10n Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-l10n
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-l10n  
      - run: |
          cd openblock-l10n
          npm ci
          npm run build
          npm link --force

      - name: gui Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-gui
          ref: refs/heads/desktopsch
          token: ${{ secrets.GH_PAT }}
          path: openblock-gui  
      - run: |
          cd openblock-gui
          npm ci
          npm install --save-dev encoding@^0.1.13 iconv browser
          npm link
          npm link openblock-vm openblock-l10n openblock-blocks

      - name: desktop Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-desktop
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-desktop  
      - run: |
          cd openblock-desktop
          npm ci
          npm link openblock-vm openblock-l10n openblock-link openblock-resource openblock-gui openblock-blocks
                   
      - name: Build and Publish
        env:
          GA_ID: ${{ secrets.GA_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          cd openblock-desktop
          npm run publish

  build-mac:
    needs: create-release
    runs-on: macos-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: blocks Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-blocks
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-blocks
      - run: |
          cd openblock-blocks
          npm ci
          npm link

      - name: link Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-link
          ref: refs/heads/qdp
          token: ${{ secrets.GH_PAT }}
          path: openblock-link
      - run: |
          cd openblock-link
          npm i
          npm link

      - name: resource Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-resource
          ref: refs/heads/qdp
          token: ${{ secrets.GH_PAT }}
          path: openblock-resource
      - run: |
          cd openblock-resource
          npm i
          npm link

      - name: vm Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-vm
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-vm  
      - run: |
          cd openblock-vm
          npm i
          npm link
          sed -i "" "s/https:\/\/tfhub.dev\/google/http:\/\/www.gstaticcnapps.cn\/tfhub-tfjs-modules\/google/g" `grep "https://tfhub.dev/google" -rl node_modules/`
          sed -i "" "s/https:\/\/tfhub.dev\/tensorflow/http:\/\/www.gstaticcnapps.cn\/tfhub-tfjs-modules\/tensorflow/g" `grep "https://tfhub.dev/tensorflow" -rl node_modules/`
          sed -i "" "s/https:\/\/tfhub.dev/https:\/\/storage.googleapis.com\/tfhub-tfjs-modules/g" `grep "https://tfhub.dev" -rl node_modules/`

      - name: l10n Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-l10n
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-l10n  
      - run: |
          cd openblock-l10n
          npm i
          npm run build
          npm link --force

      - name: gui Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-gui
          ref: refs/heads/desktopsch
          token: ${{ secrets.GH_PAT }}
          path: openblock-gui  
      - run: |
          cd openblock-gui
          npm i
          npm install --save-dev encoding@^0.1.13 iconv browser
          npm link
          npm link openblock-vm openblock-l10n openblock-blocks
      
      - name: desktop Install
        uses: actions/checkout@v2
        with: 
          repository: aopu-edu/openblock-desktop
          ref: refs/heads/sch
          token: ${{ secrets.GH_PAT }}
          path: openblock-desktop  
      - run: |
          cd openblock-desktop
          npm i
          npm link openblock-vm openblock-l10n openblock-link openblock-resource openblock-gui openblock-blocks

      - name: Build and Publish
        env:
          GA_ID: ${{ secrets.GA_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: |
          cd openblock-desktop
          npm run publish
